# Homework 05
In this exercise, you will demonstrate your learning by solving probability problems. Many of these will be math problems. You can nicely format your answers in Markdown cells using LaTeX-like commands. 

Some particular LaTeX commands you might find useful include:
- To display an inline math expression, enclose the content in single dollar signs, e.g., $x^2+4=8$ (Double click to display).
- To display a single-line centered math expression, enclose the content in double dollar signs like $$P(X > 5) = \frac{1}{6}.$$
- To display a multi-line math expression, use `\begin{aligned}` and `\end{aligned}`, use `\\` to change lines, put `&` wherever you want the lines to align, and enclose all this in single dollar signs. See the example below. Note that this is not normally what people would use in a pure LaTeX environment (it is an overkill), but doing this makes sure your solutions actually render on Gradescope for easy grading.
- Another way to display multi-line math expressions is by enclosing the equation inside double dollar signs. Use `\\` to change lines, `&` is not required here. See example below.
- To write a fraction, use `\frac{numerator}{denominator}` like $\frac{3}{4}$.
- To write set intersection and union, use `\cap` and `\cup` respectively, like $A \cap B$ and $A \cup B$.
- To write a bar over something (like a set complement), use `\overline{}` like in $\overline{E}$.
- To write a subscript or superscript, use `_{}` or `^{}` as in $X_{n}$ or $X^{2}$.
- To write a sum or product, use `\sum` or `\prod` as in $\sum_{i=1}^{n} X_i$ or $\prod_{i=1}^{n} X_i$.
- To write text inside math expressions, use `\text{}` as in $P(D \text{ is even})$.
- You can double click on this cell to get an example of the syntax of the commands mentioned above.

If you are new to LaTeX, see the [overleaf documentation for mathematical expressions](https://www.overleaf.com/learn/latex/mathematical_expressions). Note that not all LaTeX commands work in Markdown cells, as they are technically not actual LaTeX environments. Hence double check in Gradescope after submission.

## Be careful while using LaTeX

- Some of common LaTeX commands like `\begin{equation}`, `\begin{align}` do not render in Gradescope. Do cross-check your code after you submit your Homework in Gradescope.
- Even if you are using `\begin{aligned}` and `\end{aligned}`, write everything inside single dollar signs.
- Gradescope mostly renders all LaTeX/Math equations written inside single dollar signs. For example: $\sum_{k=1}^n x_n^2$.
- Don't use dollar sign to indicate US Dollars, use USD/dollars/unit money instead. Gradescope sees dollar sign as math syntax and will render your work poorly.

## Show your work!
Show your work and/or briefly explain your answers. To get full credit you must first translate the problem into a probability formula. See the worked examples for how to best show your work. In general you will not receive full credit for numeric answers with no accompanying work or justification (math, code, explanation), and we can't give you partial credit if you don't show your work.

For example, question 1.4 in the worked examples has you calculate the probability of "A die roll greater than or equal to 3 or a coin toss of tails (possibly both)." A full credit answer to this would be:

#### Using `\begin{aligned}` and `\end{aligned}` inside single dollar signs

$\begin{aligned}
P(D \geq 3 \cup C = \text{tails}) &= P(D \geq 3) + P(C = \text{tails}) - P(D \geq 3 \cap C = \text{tails}) \\
&= \frac{2}{3} + \frac{1}{2} - \frac{2}{3} \times \frac{1}{2} = \mathbf{\frac{5}{6} \approx 0.83}.
\end{aligned}$

#### Using double dollar signs

$$
P(D \geq 3 \cup C = \text{tails}) = P(D \geq 3) + P(C = \text{tails}) - P(D \geq 3 \cap C = \text{tails}) \\
= \frac{2}{3} + \frac{1}{2} - \frac{2}{3} \times \frac{1}{2} = \mathbf{\frac{5}{6} \approx 0.83}.
$$

## Note

##### If your answer renders poorly on Gradescope, you may lose points. Please check your code rendering after you submit your Homework in Gradescope.

## Question 1 (2 points auto-graded, 2 points manually graded per subquestion)
Suppose 600 individuals are on a cruise. Of the individuals:
- 300 go snorkling,
- 450 have lunch at the restaurant,
- 200 go dancing,
- 200 go snorkling and have lunch at the restaurant,
- 100 go snorkling and go dancing,
- 100 have lunch at the restaurant and go dancing,
- 50 go snorkling, have lunch at the restaurant, and go dancing.

For each of the following, compute the probability that an individual chosen uniformly at random:
1. goes snorkling and has lunch at the restaurant,
2. does not have lunch at the restaurant,
3. goes snorkling or goes dancing,
4. has lunch at the restaurant but does not go snorkling, 
5. goes dancing given that they have lunch at the restaurant.

For the autograder, in the code cell, put question 1's answer in the variable `q1_1`, question 2's answer in `q1_2`, and so on. Show your work in the Markdown cell.

In [1]:
# Code for question 1 (or can use a hand calculator and show work)


q1_1 = 1/3
q1_2 = 1/4
q1_3 = 2/3
q1_4 = 5/12
q1_5 = 2/9

<!-- BEGIN QUESTION -->

## Answer 1

q1_1 = $\begin{aligned} P(\text{Snorkling and Lunch}) &= \frac{200}{600} = \frac{1}{3} \approx 0.333. \end{aligned}$ 

q1_2 = $\begin{aligned} P(\text{Not Lunch}) &= P(\Omega) - P(\text{Lunch}) = 1 - \frac{450}{600} = \frac{150}{600} = \frac{1}{4} = 0.25. \end{aligned}$

q1_3 = $\begin{aligned} P(\text{Snorkling or Dancing}) &= P(\text{Snorkling}) \cup P(\text{Lunch}) - P(\text{Snorkling}\cap\text{Dancing})= \frac{300}{600} + \frac{200}{600} - \frac{100}{600} = \frac{400}{600} = \frac{2}{3} \approx 0.667. \end{aligned}$

q1_4 = $\begin{aligned} P(\text{Lunch and Not Snorkling}) &= \frac{450}{600} - \frac{200}{600} = \frac{250}{600} = \frac{5}{12} \approx 0.417. \end{aligned}$ 

q1_5 = $\begin{aligned} P(\text{Dancing | Lunch}) &= \frac{P(\text{Dancing and Lunch})}{P(\text{Lunch})} = \frac{\frac{100}{600}}{\frac{450}{600}} = \frac{1}{6} \times \frac{4}{3} = \frac{4}{18} = \frac{2}{9} \approx 0.222. \end{aligned}$

<!-- END QUESTION -->

## Question 2 (2 points auto-graded, 2 points manually graded per subquestion)

1. Consider a rare genetic disorder that occurs with 5% probability. Individuals with the genetic disorder have a 60% probability to develop a particular medical condition whereas individuals without the disorder only have a 10% probability to develop the medical condition. What is the probably that a random individual from the entire population will develop the medical condition?


2. Suppose that for a random student, there is an 80% probability of passing the final exam, a 90% probability of passing the course, and a 99% probability of passing the course given that the student passes the final exam. Given that a student passed the course, what is the probability that the student did not pass the final exam?  


3. Suppose that 10% of the cars produced on an assembly line have some defect. The car manufacturer has a test for checking for defects. For cars with defects, it correctly finds the defect with 99% probability. However, for cars without defects, the test incorrectly reports a defect with 5% probability.  What is the probability that a car has no defect given that the test reports that it has a defect?

For the autograder, in the code cell, put question 1's answer in the variable `q2_1` and so on. Show your work in the Markdown cell.

In [2]:
# Code for question 2 (or can use a hand calculator and show work)

q2_1 = 0.125
q2_2 = 0.12
q2_3 = 0.3125

<!-- BEGIN QUESTION -->

## Answer 2

q2_1 = $\begin{aligned} P(\text{Disorder}) = 0.05, P(\text{Condition | Disorder}) = 0.60, P(\text{Condition | Not Disorder}) = 0.10 \end{aligned}$ 

$\begin{aligned} P(\text{Condition}) = P(\text{Condition | Disorder}) \times P(\text{Disorder}) + P(\text{Condition | Not Disorder}) \times P(\text{Not Disorder}) = \end{aligned}$

$\begin{aligned} 0.60 \times 0.05 + 0.10 \times .95 = 0.125 \end{aligned}$



q2_2 = $\begin{aligned} P(\text{Pass Final}) = 0.80,P(\text{Pass Course}) = 0.90,P(\text{Pass Course | Pass Final}) = 0.99 \end{aligned}$

$\begin{aligned} P(\text{Not Pass Final | Pass Course}) = 1 - P(\text{Pass Final | Pass Course})\end{aligned}$

$\begin{aligned} P(\text{Pass Final | Pass Course}) = \frac{P(\text{Pass Course | Pass Final}) \times P(\text{Pass Final})}{P(\text{Pass Course})} = \frac{0.99 \times 0.80}{0.90} = \frac{0792}{0.90} = 0.88. \end{aligned}$

$\begin{aligned} P(\text{Not Pass Final | Pass Course}) = 1 - P(\text{Pass Final | Pass Course}) = 1 - 0.88 = 0.12 \end{aligned}$



q2_3 = $\begin{aligned} P(\text{Defect}) = 0.10,P(\text{Find Defect | Defect}) = 0.99,P(\text{Find Defect | Not Defect}) = 0.05 \end{aligned}$

$\begin{aligned} P(\text{Find Defect}) = P(\text{Find Defect | Defect}) \times P(\text{Defect}) + P(\text{Find Defect | Not Defect}) \times P(\text{Not Defect}) = 0.99 \times 0.10 + 0.05 \times 0.90 = 0.144\end{aligned}$

$\begin{aligned} P(\text{Not Defect | Find Defect}) = \frac{P(\text{Find Defect | Not Defect}) \times P(\text{Not Defect})}{P(\text{Find Defect})} = \frac{0.045}{0.144} = 0.3125\end{aligned}$

<!-- END QUESTION -->

## Question 3 (2 points auto-graded, 2 points manually graded per subquestion)
1. Suppose you are playing a game of chance. You roll a single fair 6-sided die. If the result is odd, you win a number of dollars equal to the die roll. If the result is even, you lose a number of dollars equal to the die roll. What is the expected number of dollars you will win or lose playing this game once? 


2. You play another game of chance. It proceeds in three rounds. In each round you roll a single fair 6-sided die. In the first round, if you roll a 1 you get 1 dollar. In the second round if you roll a 2 you get 2 dollars. In the third round if you roll a 3 you get 3 dollars. If at the end you have not won any of the three rounds, you lose 3 dollars. What is the expected number of dollars you will win or lose playing this game once?

For the autograder, in the code cell, put question 1's answer in the variable `q3_1` and question 2's answer in `q3_2`. Show your work in the Markdown cell.

In [3]:
# Code for question 2 (or can use a hand calculator and show work)

q3_1 = -0.50
q3_2 = -53/72

<!-- BEGIN QUESTION -->

## Answer 3

q3_1 = $\begin{aligned} E = \frac{1}{6}(1+3+5-2-4-6)=\frac{1}{6}(9-12)=\frac{-3}{6}=-0.50 \end{aligned}$

q3_2 = $\begin{aligned} E = 1 \times \frac{1}{2} + 2 \times \frac{1}{6} + 3 \times \frac{1}{6} - 3 \times (\frac{5}{6})^3 = \frac{6}{6} - 3 \times \frac{125}{216} = 1 - \frac{375}{216} = -\frac{159}{216} = -\frac{53}{72} \end{aligned}$

<!-- END QUESTION -->

## Question 4 (2 points auto-graded, 2 points manually graded)
Suppose you toss a coin $n$ times and observe that 51% of the time the result is heads. Assuming $n$ is large enough to use the central limit theorem, how large would $n$ need to be before you could conclude that the probability that the coin is fair (50/50 percent chance of heads or tails) is at most 5%? 

*Hint: It may help to define an appropriate random variable whose expectation is the quantity of interest based on a fair coin toss and calculate its variance.*

For the autograder, in the code cell, put your answer in the varialbe `q4`. Show your work in the Markdown cell.

In [4]:
# Code for question 4 (or can use a hand calculator and show work)

q4 = 9604

<!-- BEGIN QUESTION -->

## Answer 4

$\begin{aligned} P(heads) = 0.5 \end{aligned}$

$\begin{aligned} \hat p \sim N\!\left(0.5,\frac{0.25}{n}\right). \end{aligned}$

$\begin{aligned} Z=\frac{\hat p-0.5}{\sqrt{0.25/n}} =\frac{0.01}{0.5/\sqrt{n}} =0.02\sqrt{n}. \end{aligned}$

$\begin{aligned}z_{0.975}=1.96.\end{aligned}$  

$\begin{aligned} 0.02\sqrt{n} \ge 1.96. \end{aligned}$

Solving:
$\begin{aligned} \sqrt{n} \ge \frac{1.96}{0.02} = 98 \therefore n \ge 98^2 = 9604. \end{aligned}$

<!-- END QUESTION -->

## Question 5 (2 points auto-graded, 2 points manually graded)
Suppose you need to take the C1 bus to East campus, and the mean waiting time for the bus at the Chapel is 10 minutes. What is the upper bound probability that you wait for more than 35 minutes for the bus to arrive?

For the autograder, in the code cell, put your answer in the variable `q5`. Show your work in the Markdown cell.

In [5]:
# Code for question 5(or can use a hand calculator and show work)

q5 = 2/7

$\begin{aligned} P(T \geq a) \leq \frac{\mathbb{E}[X]}{a}\end{aligned}$

$\begin{aligned} X = \text{waiting time, }\mathbb{E}[X] = 10 \text{ minutes, } a = 35 \text{ minutes} \end{aligned}$

$\begin{aligned} P(T \geq 35) \leq \frac{10}{35} = \frac{2}{7} \end{aligned}$

<!-- END QUESTION -->

## Question 6 (2 points auto-graded, 3 points manually graded)
In the US presidential election, there are typically two candidates: a Democratic candidate and a Republican candidate. Each state has a number of electoral college votes. The candidate who wins the most votes in a state receives all of the electoral college votes for that particular state (there are a couple of exceptions, but to keep things simple we will assume this is how it works for all states). A candidate who wins at least 270 electoral college votes wins the national election. 

### The Data
Below we import the `polls.csv` dataset describing the 2020 US presidential election and preview the first few rows. For each of the 50 states in the USA plus Washington D.C. (which has electoral college votes like a state), the dataset records:

- `d_percent`: The percent of polled voters indicating they will vote for the Democratic candidate in the 2020 presidential election.

- `r_percent`: The percent of polled voters indicating they will vote for the Republican candidate in the 2020 presidential election.

- `ec_weight`: The number of electoral college votes controlled by the particular state.  

### What you will do
**In this question, you will write a Monte Carlo simulation to understand the probabilities of the following three events.** This is based roughly on the idea of computational models for predicting election outcomes such as those you may have seen recently in the news. 

- $D$: the Democratic candidate wins at least 270 electoral college votes (and thus the presidential election);

- $R$: the Republican candidate wins at least 270 electoral college votes (and thus the presidential election); 

- $U$: neither candidate gets 270 electoral college votes and the election is undecided.

### How you will do it
To do so, model the uncertainty in the poll numbers as follows. For each simulation:

1. For each state independently draw 0-mean normally distributed random `noise` for a given standard deviation estimate $\sigma$. You can do so, for example, using [numpy.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html). This reflects the assumption that the poll numbers are not certain and could vary in either direction by one or two standard deviations.


2. Add `noise` (independently for each state) to `d_percent` and subtract `noise` from `r_percent`. So if you get `noise = 1.5`, `d_percent = 42`, and `r_percent = 57` you would get `43.5` for the new `d_percent` and `55.5` for the new `r_percent`. 

Then for a given simulation you can check which of $D$, $R$, or $U$ occur by checking, for each state, which candidate gets a larger share of the vote, and adding up their electoral votes accross all of the states.

Make sure that **each simulation starts with the original values** from the `polls` dataset, not the results from the previous simulation. 

Code the simulation and then **run 10,000 simulations for each of the following values of $\sigma$: 1, 5, and 10. For each simulation, record which of $D$, $R$, and $U$ occurred.** Summarize the results by creating three lists `q6_1`, `q6_5`, and `q6_10`, one for each $\sigma$. More specifically, `q6_1 = [q6_1d, q6_1r, q6_1u]`, where `q6_1d` is the number of simulations where $\sigma = 1$ and $D$ happened, `q6_1r` is the number of simulations where $\sigma = 1$ and $R$ happened, and `q6_1u` is the number of simulations where $\sigma = 1$ and $U$ happened, and so on. You should therefore have a total of 9 values in these 3 lists.

It may take a few seconds for your simulations to run, but if they are running for minutes, you are likely writing inefficient loops instead of taking advantage of efficient Pandas and Numpy operations. You will need one loop over the 10,000 simulations but should not need any others. You will **lose manual grading points** if you use a `for` loop to index into the dataframe.

*Hint: We recommend that you write the following functions:*

1. *A function that takes a `DataFrame` of votes where the noise has already been added and returns who has won based on the electoral college votes per state.*


2. *A function that simulates an election by taking a `DataFrame` of vote/poll data and a standard deviation and adds noise.*


3. *A function that runs all the simulations for a specific standard deviation.*

*It'll make your code easier to write and understand.*

### Submission Instructions
For the sake of consistency and easy debugging, we recommend that you do the following when you are ready to submit:

1. Surround your code with triple quotes (e.g. `''' <code here in many lines> '''`, see example below).


2. Outside the triple quotes, manually assign the values of `q6_1`, `q6_5`, and `q6_10` with the values of the last time you ran your code.

This keeps your code (as comments) in your notebook so that it can be manually graded, and also prevents the autograder from timing out and giving you a 0. You do not need to write anything in a Markdown cell for this question.

In [6]:
import pandas as pd
polls = pd.read_csv("polls.csv")
polls.head()

        state  d_percent  r_percent  ec_weight
0     alabama         37         62          9
1      alaska         44         55          3
2     arizona         50         49         11
3    arkansas         35         64          6
4  california         64         35         55

In [7]:
import numpy as np

# This is an example of convert code into a string so it is not run
'''
def election_won(df):
    d_wins = df["d_percent"] > df["r_percent"]
    
    d_ec = df.loc[d_wins, "ec_weight"].sum()
    r_ec = df.loc[df["r_percent"] > df["d_percent"], "ec_weight"].sum()
    
    if d_ec >= 270:
        return "D"
    elif r_ec >= 270:
        return "R"
    else:
        return "U"

def sim(df, s):
    sim_df = df.copy()
    
    noise = np.random.normal(0, s, size=len(sim_df))
    
    sim_df["d_percent"] = sim_df["d_percent"] + noise
    sim_df["r_percent"] = sim_df["r_percent"] - noise
    
    return election_won(sim_df)

def run_sim(df, s, n_sims=10000):
    d_count = 0
    r_count = 0
    u_count = 0
    
    for _ in range(n_sims):
        result = sim(df, s)
        
        if result == "D":
            d_count += 1
        elif result == "R":
            r_count += 1
        else:
            u_count += 1
    
    return [d_count, r_count, u_count]

q6_1 = run_sim(polls, 1)
q6_5 = run_sim(polls, 5)
q6_10 = run_sim(polls, 10)
'''

q6_1 = [9237, 593, 170]
q6_5 = [8220, 1677, 103]
q6_10 = [7428, 2484, 88]

# Leave these here for manual grading
print(q6_1)
print(q6_5)
print(q6_10)

[9237, 593, 170]
[8220, 1677, 103]
[7428, 2484, 88]

<!-- BEGIN QUESTION -->

#### Copy and paste your code in the cell below inside triple quotes ''' ..code.. '''

_Type your answer here, replacing this text._

<!-- END QUESTION -->

## Question 7 (4 points auto-graded, 8 points manually graded)

You will be using a Pokemon dataset (pokemon_attributes.csv) in this question. 

This data contains information on many of the pokemon in the Pokemon franchise. As a brief explanation, pokemon are monsters that can transform/evolve into a fixed series of other pokemon. The series is at most three pokemon long (eg., Charmander -> Charmeleon -> Charizard), and some do not evolve at all (eg., Minior). Each pokemon has one or two types associated with it, such as grass, water, poison, etc, as well as a classification from the Sun and Moon Pokedex, such as Seed, Lizard, Flame, etc. When a pokemon evolves, it may also change or swap out a type. Each pokemon also has stats associated with it. The Pokemon Attributes.csv's columns are as follows:

1. **Name** & **Japanese Name** - pokemon's name
1. **Percentage Male** - The percentage of male in that species. A `nan` represents the pokemon is genderless.
1. **Type1** - The pokemon's primary type
1. **Type2** - The pokemon's secondary type
1. **Height, weight** - The height and weight of the pokemon, in meters and kilograms respectively. 
1. **Capture Rate** - The capture rate of the pokemon (Notice that `Minior` has a separate capture rate for Meteorite form and Core form).
1. **Base Egg Steps** - The number of steps required to hatch an egg of the pokemon
1. **Base Happiness** - The base happiness of the pokemon
1. **Abilities** - a JSON-stringified list of abilities that the pokemon is capable of having. 
1. **Experience Growth** - The experience growth of the pokemon
1. **HP** - The base amount of Health Points the pokemon has
1. **Attack** - The pokemon's base attack
1. **Defense** - The pokemon's base defense
1. **Sp. Attack** - The pokemon's base special attack
1. **Sp. Defense** - The pokemon's base special defense
1. **Speed** - The pokemon's base speed
1. **Generation** - The numbered generation which the Pokemon was first introduced
1. **Is Legendary** - Denotes if the pokemon is legendary
1. **Classification** - The Classification of the Pokemon as described by the Sun and Moon Pokedex

In this question, you will run a Monte Carlo Simulation. Your code will generate its own subset of Pokemon. Describe a scenario and then calculate the probability of that scenario happening with the following constraints:

1. Use at least 2 columns of data as part of your scenario.
1. The scenario should have some kind of inequality in it, such as "There are more fire Pokemon than grass"
1. The scenario should involve more than one Pokemon.
1. You may filter the data if you wish, but there must be at least 100 rows in the data set you simulate over. The column(s) used in the filtering can count towards your "at least 2 columns" constraint. If you filter by a random sample, you must explain why in the written portion of this question.
1. Run enough simulations that you are confident in your answer within 0.1% (this code prints things as a decimal, so 0.1% is the third digit after the decimal). Do not change the `count` and `sims` variable names. The autograder uses these to do its sanity check.

See the written portion of this question to see what you must explain.

Here are some example scenarios that you **cannot** use but to help make clear what you need to do:

1. What is the probability that a pack of 20 Generation 1 Pokémon cards (which can have duplicates) has more water-type than fire-type Pokémon?
1. What is the probability that in a random deck of 30 unique Pokémon cards, it has >= 20% grass Pokémon and the mean height of all the Pokémon is >= 1?

**Note**: You are allowed to use a for or while loop for this question.

In [8]:
pokemon = pd.read_csv('pokemon_attributes.csv')
pokemon.head()

,name,japanese_name,percentage_male,type1,type2,height_m,weight_kg,capture_rate,base_egg_steps,base_happiness,...,experience_growth,hp,attack,defense,sp_attack,sp_defense,speed,generation,is_legendary,classification
0,Bulbasaur,Fushigidaneフシギダネ,88.1,grass,poison,0.7,6.9,45,5120,70,...,1059860,45,49,49,65,65,45,1,0,Seed Pokémon
1,Ivysaur,Fushigisouフシギソウ,88.1,grass,poison,1.0,13.0,45,5120,70,...,1059860,60,62,63,80,80,60,1,0,Seed Pokémon
2,Venusaur,Fushigibanaフシギバナ,88.1,grass,poison,2.0,100.0,45,5120,70,...,1059860,80,100,123,122,120,80,1,0,Seed Pokémon
3,Charmander,Hitokageヒトカゲ,88.1,fire,NaN,0.6,8.5,45,5120,70,...,1059860,39,52,43,60,50,65,1,0,Lizard Pokémon
4,Charmeleon,Lizardoリザード,88.1,fire,NaN,1.1,19.0,45,5120,70,...,1059860,58,64,58,80,65,80,1,0,Flame Pokémon

## Answer 7: Code

In [9]:

# Add and update whatever code you need into this skeleton
pokemon = pokemon[pokemon["is_legendary"] == False].reset_index(drop=True)

count = 0
sims = 50000

sample_size = 10
dual_type = 0.30
min_dual_count = int(np.ceil(sample_size * dual_type))

for i in range(sims):
    sample = pokemon.sample(sample_size, replace=False)

    dual_count = sample["type2"].notnull().sum()

    if dual_count >= min_dual_count:
        count += 1
    
    # Leave this if statement here for grading to show you
    # are confident in your answer within 0.1%
    if (i+1) % 1000 == 0:
        print(i+1, count/(i+1))

# Leave this here to help with grading.
print('Final result:', count/sims)

1000 0.947
2000 0.9445
3000 0.9433333333333334
4000 0.9425
5000 0.9456
6000 0.9463333333333334
7000 0.9471428571428572
8000 0.949
9000 0.9487777777777778
10000 0.9491
11000 0.9499090909090909
12000 0.9503333333333334
13000 0.9505384615384616
14000 0.9504285714285714
15000 0.9501333333333334
16000 0.9503125
17000 0.9502941176470588
18000 0.9508333333333333
19000 0.9504736842105264
20000 0.9505
21000 0.9507142857142857
22000 0.950590909090909
23000 0.9508260869565217
24000 0.9505
25000 0.95048
26000 0.9507692307692308
27000 0.9507777777777778
28000 0.9508214285714286
29000 0.9509310344827586
30000 0.9507
31000 0.9506129032258065
32000 0.95040625
33000 0.9505757575757576
34000 0.9503529411764706
35000 0.9501428571428572
36000 0.9504444444444444
37000 0.9506216216216217
38000 0.9506315789473684
39000 0.9508461538461539
40000 0.95065
41000 0.9504878048780487
42000 0.9504523809523809
43000 0.9500697674418604
44000 0.9502272727272727
45000 0.9501555555555555
46000 0.9500217391304348
47000 0.9499574468085107
48000 0.9499166666666666
49000 0.9500816326530612
50000 0.95008
Final result: 0.95008

<!-- BEGIN QUESTION -->

## Answer 7: Written Portion
Do the following:
1. Provide a 1-3 sentence explanation of the scenario. Be explicit in whether this scenario requires with or without replacement and why.
1. State the probability your simulation found, rounded to the nearest 0.1%, and explain why you are confident in your answer.

My scenario requires drawing 10 non-legendary Pokemon without replacement and check whether at least 30% are dual-type (`type2` is not `null`). So I use `is_legendary` to filter the initial population of pokemon and `type2` to test the event. I used sampling without replacement because I'm modeling a group of 10 distinct Pokemon chosen from the data, in order to reflect chosing 10 different Pokemon each time. This wouldn't make sense if it a Pokemon could be selected multiple times.

The simulation found a probability of around 92.2%. I'm confident in this answer because I ran 50,000 simulations with a standard errorr of $\begin{aligned} \approx 0.00095 \end{aligned}$ which is $\begin{aligned} \lt 0.001  \end{aligned}$ , the standard error required.

<!-- END QUESTION -->

## Submitting

For the last question, make sure you are using a `for` loop only for the 10,000 simulations. Do not use a `for` loop to iterate over the dataframe.

You should make sure any code that you write to answer the questions is included in this notebook.  You are **required** to go to the Kernel option and choose **"Restart & Run All"** before submission. Double check that your entire notebook runs correctly and generates the expected output. Finally, make sure to save your work (timestamp at the top tells you the last checkpoint and whether there are unsaved changes). When you finish, submit your assignment at Gradescope. **Submissions not prepared correctly as above will lose points.**

<!-- BEGIN QUESTION -->

# AI Disclosure

Use the **Artificial Intelligence Disclosure (AID) Framework** to explain your use of AI on this assignment. Other headings you can use include:

- *Debugging:* Using AI to help you fix your code so that it works. You should state how you used it for this purpose.

Here are some examples:

*Artificial Intelligence Tools:* ChatGPT v5 via chatgpt.com. *Conceptualization:* I gave chatgpt.com the election data set and asked it for ideas on interesting statistics I could get from the data. *Methodology:* I asked it for help on how to write the code to get the statistic I chose, but I wrote the code myself. *Writing — Review & Editing:* I wrote out my explanation for what the statistic meant, then gave that text and the rubric to chatgpt and asked it to give me feedback on how to update the explanation to conform to the rubric.

*Artificial Intelligence Tools:* ChatGPT v4o via DukeGPT. *Information Collection:* DukeGPT was used to find the function needed to get the index value of the maximum value of a Series and the syntax needed to filter rows in a pandas dataframe using multiple columns. *Debugging:* DukeGPT was used to help me find a bug in my code for Q1 where I copied in the code and error, stated what the code should do, and asked for help.


*Artificial Intelligence Tools*: ChatGPT v5 via chatgpt.com. *Methodology:* I asked it for help on clarifying the concept in Q4, and assitance to write the LaTeX code, but I wrote the code myself. *Conceptualization*: I gave chatgpt.com the `pokemon_attributes.csv` file and asked it for ideas on events I could calculate from the data. *Debugging*: ChatGPT was used to help me find a bug in my code for Q6 where I copied in the code and error, stated what the code should do, and asked for help. *Writing—Review & Editing*: I gave my explanation and my code for Q7, as well as the rubric to ChatGPT and asked it to give me feedback on how to update the explanation to conform to the rubric.